# Generated by Django 3.1.5 on 2021-04-10 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_id', models.CharField(max_length=20)),
                ('department_name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation_id', models.CharField(max_length=20)),
                ('designation_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eid', models.CharField(max_length=25)),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=20)),
                ('eemail', models.EmailField(max_length=25)),
                ('eage', models.CharField(max_length=25)),
                ('edob', models.DateTimeField()),
                ('edoj', models.DateTimeField()),
                ('esalary', models.DecimalField(decimal_places=2, max_digits=20)),
                ('edepartment', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.department')),
                ('edesignation', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.designation')),
            ],
        ),
    ]
